Repository paddy-exe/ShaderFunction-Extras, pull requests merged in 2023-03, with the labels that each got.

#1 Update README with detailed information
  README.md
Labels: documentation, enhancement

#3 Add Funding info and CI support for releases
  .github/FUNDING.yml
  .github/workflows/release.yml
Labels: enhancement

#5 Fix CI zip process
  .github/workflows/release.yml
Labels: bug

#6 Fix CI release
  .github/workflows/release.yml
Labels: bug

#7 Fix CI release
  .github/workflows/release.yml
Labels: bug

#8 Create Archive to upload
  .github/workflows/release.yml
Labels: bug

#11 Added functions and added provided function list to README
  README.md
  addons/ShaderFunction-Extras/UV/LicenseInfo.md
  addons/ShaderFunction-Extras/UV/uv.gdshaderinc
  addons/ShaderFunction-Extras/Wave/wave.gdshaderinc
Labels: documentation, enhancement

#14 Add file path log to CI
  .github/workflows/release.yml
Labels: ci-enhancement

#15 Remove uv inputs from blend modes and renamed Color Conversion
  README.md
  addons/ShaderFunction-Extras/Color/blend_modes.gdshaderinc
  addons/ShaderFunction-Extras/Color/color_adjustment.gdshaderinc
Labels: 🐛 bug, 📚 documentation, ⚠️ compat-breaking

#16 Add showcase gif on how to integrate the gdshaderinc files in written shaders
  README.md
Labels: 📚 documentation, ⭐ enhancement

#17 Fix release CD workflow
  .github/workflows/release.yml
Labels: 🐛 ci-bug

#19 Added saturate and fixed depth bug
  README.md
  addons/ShaderFunction-Extras/Utility/utility.gdshaderinc
Labels: 🐛 bug

#20 Added vertex_billboard function
  README.md
  addons/ShaderFunction-Extras/Utility/utility.gdshaderinc
Labels: 📚 documentation, ⭐ enhancement
